- name: Display job information
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add ansible task delay
      ansible.builtin.pause:
        seconds: 10
    
    - name: Show job ID
      ansible.builtin.debug:
        msg: "Job ID: {{ awx_job_id }}"

    - name: Show job launch type
      ansible.builtin.debug:
        msg: "Launch Type: {{ awx_job_launch_type }}"
