- name: Display workflow information
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add ansible task delay
      ansible.builtin.pause:
        seconds: 10

    - name: Show workflow ID
      ansible.builtin.debug:
        msg: "Workflow ID: {{ awx_workflow_job_id }}"

    - name: Show job launch type
      ansible.builtin.debug:
        msg: "Launch Type: {{ awx_job_launch_type }}"
