---
- name: Get stats
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    # # Using the Tower env names for backwards compatibility
    controller_hostname: "{{ lookup('ansible.builtin.env', 'TOWER_HOST') }}"
    controller_username: "{{ lookup('ansible.builtin.env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('ansible.builtin.env', 'TOWER_PASSWORD') }}"
    controller_validate_certs: "{{ lookup('ansible.builtin.env', 'TOWER_VERIFY_SSL') | default(false) }}"
    discovered_inv_ids: []
    approved_inv_ids: [1, 2, 4, 5]
    discovered_inv_names: []
    approved_inv_names: ["Demo Inventory", "EDA Demo", "localhost", "Virtual_Platform"]

  tasks:
    - name: Get number of JT
      ansible.builtin.uri:
        url: "{{ controller_hostname }}/api/v2/inventories/?format=json"
        method: GET
        force_basic_auth: true
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        return_content: true
        headers:
          Content-Type: application/json
        validate_certs: false
      register: r_metrics

    - name: Debug r_metrics inv count
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: r_metrics.json.count

    - name: Debug r_metrics inv ids
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: r_metrics.json.results[item].id
      loop: "{{ range(0, r_metrics.json.count) | list }}"

    - name: Set fact called inv_ids with list from r_metrics.json.results[item].id
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        discovered_inv_ids: "{{ discovered_inv_ids + [r_metrics.json.results[item].id] }}"
      loop: "{{ range(0, r_metrics.json.count) | list }}"

    - name: Debug inv_ids var
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: discovered_inv_ids

    - name: Compare discovered_inv_ids and approved_inv_ids abd debug difference
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ discovered_inv_ids | difference(approved_inv_ids) }}"

    - name: Set fact called not_approved_inv_ids form discovered_inv_ids | difference(approved_inv_ids)
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        not_approved_inv_ids: "{{ discovered_inv_ids | difference(approved_inv_ids) }}"

    - name: Set fact called discovered_inv_names with list from r_metrics.json.results[item].name
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        discovered_inv_names: "{{ discovered_inv_names + [r_metrics.json.results[item].name] }}"
      loop: "{{ range(0, r_metrics.json.count) | list }}"

    - name: Debug discovered_inv_names var
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: discovered_inv_names

    - name: Set fact called not_approved_inv_names form discovered_inv_names | difference(approved_inv_names)
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        not_approved_inv_names: "{{ discovered_inv_names | difference(approved_inv_names) }}"

    - name: Debug not_approved_inv_names var
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: not_approved_inv_names

    # - name: Remove all  not approved inventories using ansible.controller collection module
    #   # Content suggestion provided by Ansible Lightspeed
    #   loop: "{{ not_approved_inv_ids }}"
    #   register: r_remove_inv
    #   failed_when: r_remove_inv.msg is not search('does not exist')
    #   awx.awx.inventory:
    #     controller_host: "{{ controller_hostname }}"
    #     controller_username: "{{ controller_username }}"
    #     controller_password: "{{ controller_password }}"
    #     validate_certs: "{{ controller_validate_certs }}"
    #     name: "{{ item }}"
    #     state: absent
    #     organization: "{{ _organization_ }}"



    # - name: Debug metrics
    #   ansible.builtin.debug:
    #     verbosity: 1
    #     msg:
    #       - "{{ r_metrics }}"
    #       - "{{ r_metrics['json']['awx_system_info'] }}"
    #       - "{{ r_metrics['json']['awx_job_templates_total'] }}"
    #       - "{{ r_metrics['json']['awx_workflow_job_templates_total'] }}"
    #       - "{{ r_metrics['json']['awx_license_instance_total'] }}"
    #       - "{{ r_metrics['json']['awx_license_instance_free'] }}"
