---
- name: Get stats
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    # # Using the Tower env names for backwards compatibility
    controller_hostname: "{{ lookup('ansible.builtin.env', 'TOWER_HOST') }}"
    controller_username: "{{ lookup('ansible.builtin.env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('ansible.builtin.env', 'TOWER_PASSWORD') }}"
    controller_validate_certs: "{{ lookup('ansible.builtin.env', 'TOWER_VERIFY_SSL') | default(false) }}"

  tasks:
    - name: Get number of JT
      ansible.builtin.uri:
        url: "{{ controller_hostname }}/api/v2/metrics/?format=json"
        method: GET
        force_basic_auth: true
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        return_content: true
        headers:
          Content-Type: application/json
        validate_certs: false
      register: r_metrics

    - name: Debug r_metrics
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        var: r_metrics

      

    - name: Debug metrics
      ansible.builtin.debug:
        verbosity: 1
        msg:
          - "{{ r_metrics }}"
          - "{{ r_metrics['json']['awx_system_info'] }}"
          - "{{ r_metrics['json']['awx_job_templates_total'] }}"
          - "{{ r_metrics['json']['awx_workflow_job_templates_total'] }}"
          - "{{ r_metrics['json']['awx_license_instance_total'] }}"
          - "{{ r_metrics['json']['awx_license_instance_free'] }}"
